import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 11.0

[font.bold] 
family = "JetBrainsMono Nerd Font"
style = "ExtraBold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "ExtraBold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Thin Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Medium"

[selection]
save_to_clipboard = true

[window.padding]
x = 10
y = 10
