import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  # "~/.config/alacritty/catppuccin-mocha.toml"
]

[font]
size = 11.0

[font.bold] 
family = "JetBrainsMono Nerd Font"
style = "ExtraBold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "ExtraBold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Thin Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Medium"

[selection]
save_to_clipboard = true

[window.padding]
x = 5
y = 5
