## Colors configuration
[colors.primary]
background = "#090b0a"
foreground = "#a6b9e7"

[colors.normal]
black   = "#090b0a"
red     = "#385F9D"
green   = "#8066B1"
yellow  = "#977CDC"
blue    = "#907FE0"
magenta = "#088CE5"
cyan    = "#2888E1"
white   = "#a6b9e7"

[colors.bright]
black   = "#7481a1"
red     = "#385F9D"
green   = "#8066B1"
yellow  = "#977CDC"
blue    = "#907FE0"
magenta = "#088CE5"
cyan    = "#2888E1"
white   = "#a6b9e7"
