# Shell variables
# Generated by 'wal'
wallpaper='/home/leuk/Pictures/wallpapers/blue-circuits.png'

# Special
background='#090b0a'
foreground='#a6b9e7'
cursor='#a6b9e7'

# Colors
color0='#090b0a'
color1='#385F9D'
color2='#8066B1'
color3='#977CDC'
color4='#907FE0'
color5='#088CE5'
color6='#2888E1'
color7='#a6b9e7'
color8='#7481a1'
color9='#385F9D'
color10='#8066B1'
color11='#977CDC'
color12='#907FE0'
color13='#088CE5'
color14='#2888E1'
color15='#a6b9e7'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
