# This file created by conda-build 3.27.0
# meta.yaml template originally from:
# /work/perseverance-python-buildout/aggregate/ruamel.yaml-feedstock/recipe, last modified Wed Nov  1 02:15:18 2023
# ------------------------------------------------

package:
  name: ruamel.yaml
  version: 0.17.21
source:
  sha256: 8b7ce697a2f212752a35c1ac414471dc16c424c9573be4926b56ff3f5d23b7af
  url: https://pypi.io/packages/source/r/ruamel.yaml/ruamel.yaml-0.17.21.tar.gz
build:
  number: '0'
  script: /work/perseverance-python-buildout/croot/ruamel.yaml_1698863605521/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/bin/python
    -m pip install . --no-deps -vv
  string: py312h5eee18b_0
requirements:
  build:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - _sysroot_linux-64_curr_repodata_hack 3 haa98f57_10
    - binutils_impl_linux-64 2.38 h2a08ee3_1
    - binutils_linux-64 2.38.0 hc2dff05_0
    - gcc_impl_linux-64 11.2.0 h1234567_1
    - gcc_linux-64 11.2.0 h5c386dc_0
    - kernel-headers_linux-64 3.10.0 h57e8cba_10
    - ld_impl_linux-64 2.38 h1181459_1
    - libgcc-devel_linux-64 11.2.0 h1234567_1
    - libgcc-ng 11.2.0 h1234567_1
    - libgomp 11.2.0 h1234567_1
    - libstdcxx-ng 11.2.0 h1234567_1
    - sysroot_linux-64 2.17 h57e8cba_10
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - bzip2 1.0.8 h7b6447c_0
    - ca-certificates 2023.08.22 h06a4308_0
    - expat 2.5.0 h6a678d5_0
    - ld_impl_linux-64 2.38 h1181459_1
    - libffi 3.4.4 h6a678d5_0
    - libgcc-ng 11.2.0 h1234567_1
    - libgomp 11.2.0 h1234567_1
    - libstdcxx-ng 11.2.0 h1234567_1
    - libuuid 1.41.5 h5eee18b_0
    - ncurses 6.4 h6a678d5_0
    - openssl 3.0.11 h7f8727e_2
    - pip 23.3 py312h06a4308_0
    - python 3.12.0 h996f2a0_0
    - readline 8.2 h5eee18b_0
    - ruamel 1.0 py312h06a4308_2
    - setuptools 68.0.0 py312h06a4308_0
    - sqlite 3.41.2 h5eee18b_0
    - tk 8.6.12 h1ccaba5_0
    - tzdata 2023c h04d1e81_0
    - wheel 0.41.2 py312h06a4308_0
    - xz 5.4.2 h5eee18b_0
    - zlib 1.2.13 h5eee18b_0
  run:
    - libgcc-ng >=11.2.0
    - python >=3.12,<3.13.0a0
test:
  commands:
    - pip check
  imports:
    - ruamel.yaml
  requires:
    - pip
about:
  description: A YAML parser/emitter that supports roundtrip preservation of comments,
    seq/map flow style, and map key order
  dev_url: https://sourceforge.net/projects/ruamel-yaml/
  doc_source_url: https://sourceforge.net/p/ruamel-yaml/code/ci/0.17.21/tree/_doc/
  doc_url: https://yaml.readthedocs.io
  home: https://sourceforge.net/projects/ruamel-yaml/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  license_url: https://sourceforge.net/p/ruamel-yaml/code/ci/0.17.21/tree/LICENSE
  summary: A YAML package for Python. It is a derivative of Kirill Simonov's PyYAML
    3.11 which supports YAML1.1
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - jakirkham
    - mbargull
    - mwcraig
    - ocefpaf
    - pelson
