#!/usr/bin/env bash

## Copyright (C) 2020-2024 Aditya Shakya <adi1090x@gmail.com>
##
## launch wofi with alt config

CONFIG="$HOME/.config/river/wofi/config"
STYLE="$HOME/.config/river/wofi/style.css"

if [[ ! `pidof wofi` ]]; then
	wofi --show drun --prompt 'Search...' --conf ${CONFIG} --style ${STYLE} --location=0
else
	pkill wofi
fi
